[package]
name = "intcode"
version = "0.3.1"
authors = ["Devon Hollowood <devonhollowood@google.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
