[package]
name = "day09"
version = "0.1.0"
authors = ["Devon Hollowood <devonhollowood@gmail.com>"]

[dependencies]
structopt = "0.1.0"
structopt-derive = "0.1.0"

[dependencies.nom]
version = "^3.2"
features = ["verbose-errors"]
