indent_style = "Block"
unstable_features = false
verbose = false
disable_all_formatting = false
skip_children = false
max_width = 80
error_on_line_overflow = true
error_on_line_overflow_comments = true
tab_spaces = 4
fn_call_width = 60
struct_lit_width = 18
struct_variant_width = 35
force_explicit_abi = true
newline_style = "Unix"
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"
impl_empty_single_line = true
trailing_comma = "Vertical"
trailing_semicolon = true
fn_empty_single_line = true
fn_single_line = false
fn_return_indent = "WithArgs"
fn_args_paren_newline = false
fn_args_density = "Tall"
array_width = 60
array_horizontal_layout_threshold = 0
type_punctuation_density = "Wide"
where_density = "Vertical"
where_single_line = false
where_layout = "Vertical"
struct_lit_multiline_style = "PreferSingle"
report_todo = "Never"
report_fixme = "Never"
chain_width = 60
chain_split_single_child = false
imports_indent = "Visual"
imports_layout = "Mixed"
reorder_extern_crates = true
reorder_extern_crates_in_group = true
reorder_imports = false
reorder_imports_in_group = false
reorder_imported_names = true
single_line_if_else_max_width = 50
format_strings = false
force_format_strings = false
take_source_hints = false
hard_tabs = false
wrap_comments = false
comment_width = 80
normalize_comments = false
wrap_match_arms = true
match_block_trailing_comma = false
match_arm_forces_newline = false
indent_match_arms = true
match_pattern_separator_break_point = "Front"
space_before_colon = false
space_after_colon = true
spaces_around_ranges = false
spaces_within_parens_and_brackets = false
use_try_shorthand = false
write_mode = "Overwrite"
color = "Auto"
condense_wildcard_suffixes = false
combine_control_expr = true
struct_field_align_threshold = 0
remove_blank_lines_at_start_or_end_of_block = true
attributes_on_same_line_as_field = true
attributes_on_same_line_as_variant = true
multiline_closure_forces_block = false
multiline_match_arm_forces_block = false
merge_derives = true
binop_separator = "Front"
required_version = "0.2.16"
